version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 4032:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bee_cash_api
    networks:
      - bee-cash-api
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: bee_cash_api
  #   networks:
  #     - bee-cash-api
networks:
  bee-cash-api: